---
global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'flink'
  static_configs:
    - targets: ['jobmanager:9249', 'taskmanager:9249']
- job_name: 'spark'
  static_configs:
    - targets: ['spark-master:4040']
  metrics_path: '/metrics/prometheus'
