---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
- job_name: 'flink'
  static_configs:
    - targets: ['jobmanager:9249', 'taskmanager:9249']
- job_name: 'spark'
  static_configs:
    - targets: ['spark:4040']
  metrics_path: '/metrics/executors/prometheus'
