# context is root folder
FROM python:alpine

WORKDIR /app/

# used by healthcheck
RUN apk --no-cache add curl

COPY src/producer/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src/producer/ ./

EXPOSE 8888

CMD [ "python", "main.py" ]
