FROM flink:1.19.0-scala_2.12-java11

# Install Python
RUN apt-get update -y && \
  apt-get install -y python3 python3-pip python3-dev && rm -rf /var/lib/apt/lists/*

# Set python3 as default version
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install PyFlink
RUN pip3 install apache-flink==1.19.0
