{
 "title": "Flink",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Latency - Query 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_custom_latency{task_name=\"TumblingEventTimeWindows____Map____query_1____Sink:_Writer\"}",
     "legendFormat": "Window 1 Day - Latency"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_custom_latency{task_name=\"TumblingEventTimeWindows____Map____query_3____Sink:_Writer\"}",
     "legendFormat": "Window 3 Days"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_custom_latency{task_name=\"TumblingEventTimeWindows____Map____query_23____Sink:_Writer\"}",
     "legendFormat": "Window 23 Days"
    }
   ]
  },
  {
   "title": "Input Records Per Second - Query 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TumblingEventTimeWindows____Map____query_1____Sink:_Writer\"}",
     "legendFormat": "Window 1 Day"
    },
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TumblingEventTimeWindows____Map____query_3____Sink:_Writer\"}",
     "legendFormat": "Window 3 Days"
    },
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TumblingEventTimeWindows____Map____query_23____Sink:_Writer\"}",
     "legendFormat": "Window 23 Days"
    }
   ]
  },
  {
   "title": "Latency - Query 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_custom_latency{task_name=\"TriggerWindow_TumblingEventTimeWindows_86400000___ListStateDescriptor_name_window_contents__defaultValue_null__serializer_org_apache_flink_api_common_typeutils_base_ListSerializer_2ca72c69___EventTimeTrigger____AllWindowedStream_impl_Query2_scala:106______query_1____Sink:_Writer\"}",
     "legendFormat": "Window 1 Day - Latency"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_custom_latency{task_name=\"TriggerWindow_TumblingEventTimeWindows_259200000___ListStateDescriptor_name_window_contents__defaultValue_null__serializer_org_apache_flink_api_common_typeutils_base_ListSerializer_2ca72c69___EventTimeTrigger____AllWindowedStream_impl_Query2_scala:106______query_3____Sink:_Writer\"}",
     "legendFormat": "Window 3 Days"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_custom_latency{task_name=\"TriggerWindow_TumblingEventTimeWindows_1987200000___ListStateDescriptor_name_window_contents__defaultValue_null__serializer_org_apache_flink_api_common_typeutils_base_ListSerializer_2ca72c69___EventTimeTrigger____AllWindowedStream_impl_Query2_scala:106______query_23____Sink:_Writer\"}",
     "legendFormat": "Window 23 Days"
    }
   ]
  },
  {
   "title": "Input Records Per Second - Query 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TriggerWindow_TumblingEventTimeWindows_86400000___ListStateDescriptor_name_window_contents__defaultValue_null__serializer_org_apache_flink_api_common_typeutils_base_ListSerializer_2ca72c69___EventTimeTrigger____AllWindowedStream_impl_Query2_scala:106______query_1____Sink:_Writer\"}",
     "legendFormat": "Window 1 Day"
    },
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TriggerWindow_TumblingEventTimeWindows_259200000___ListStateDescriptor_name_window_contents__defaultValue_null__serializer_org_apache_flink_api_common_typeutils_base_ListSerializer_2ca72c69___EventTimeTrigger____AllWindowedStream_impl_Query2_scala:106______query_3____Sink:_Writer\"}",
     "legendFormat": "Window 3 Days"
    },
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"TriggerWindow_TumblingEventTimeWindows_1987200000___ListStateDescriptor_name_window_contents__defaultValue_null__serializer_org_apache_flink_api_common_typeutils_base_ListSerializer_2ca72c69___EventTimeTrigger____AllWindowedStream_impl_Query2_scala:106______query_23____Sink:_Writer\"}",
     "legendFormat": "Window 23 Days"
    }
   ]
  }
 ]
}